### PR TITLE
Refining polybar configuration

### PR DESCRIPTION
**Pull request by dharmx**
# Changes
 - Added base16 color architecture (currently nordtheme)
 - Relativised absolute/hardcoded color values
 - Segregated bar components, settings, fonts and colors into several independant files.
 
## Alert!
 - Provide your own path to the files.
 - You may need to tweak the colors and when you do remember to change from colors.ini
 
## Tree structure
polybar
├── bars
│   ├── external-fonts.ini
│   ├── external.ini
│   ├── main-fonts.ini
│   └── main.ini
├── colors.ini
├── config.ini
├── launch.bash
├── modules.ini
├── scripts
│   └── polywins.sh
├── separators.ini
├── settings.ini
└── tray.ini

## Include structure
```
                                |---------> tray.ini
                                |---------> settings.ini
                                |---------> separators.ini
config.ini ---------------------|---------> modules.ini 
                                |---------> colors.ini
			        |
			        |---------> external.ini ---------> external-fonts.ini
			        |---------> main.ini     ---------> main-fonts.ini
```

### CODE REVIEW

**Comment by dharmx** [comment]
OOF... I had also created a dummy readme. Sorry, about that.

**Comment by p4rthh** [comment]
No problem with the Readme. I'll fix everything up!

**Comment by p4rthh** [comment]
Thanks @pagankeymaster, its done!

**Comment by dharmx** [comment]
Noice!

**Pull request merged**
